### ISSUE TITLE
Stratagem GUI should be hidden if not available

### ISSUE THREAD

**Issue by utopiabound** [whamcloud/integrated-manager-for-lustre#1160]
Stratagem info: "Scan Filesystem Now", "Top inode Users", "File Size Distribution",  ... is all shown in filesystem detail page, but there's no stratagem profiles or components installed on servers.

**To Reproduce**
1. Create filesystem in managed mode.
2. See Stratagem components

**Expected behavior**
No stratagem components

**Comment by utopiabound** [comment]
Here is json of /api/host/
[api-hosts.json.log](https://github.com/whamcloud/integrated-manager-for-lustre/files/3522599/api-hosts.json.log)
Json of /api/target/
[api-target.json.log](https://github.com/whamcloud/integrated-manager-for-lustre/files/3522600/api-target.json.log)

**Comment by jgrund** [comment]
The problem is within this code:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/51e958665efdbdcf1d2abb982cee82bf668a8acf/iml-wasm-components/iml-fs/src/fs_detail_page.rs#L92-L96

A filter checking `mdt.active_host_name == x.address` is used, however in this case `active_host_name` is fqdn and address is shortname so no filters match. 

After this filter, all remaining items are checked to be `stratagem_server`. Since there are no items, this returns true.

**Comment by jgrund** [comment]
The `active_host_name` property comes from here:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/51e958665efdbdcf1d2abb982cee82bf668a8acf/chroma_api/target.py#L374-L378

It uses the `label` so, it seems that's how we should do comparisions.

**Comment by jgrund** [comment]
In addition, we should be checking there are still some hosts left before checking that all remaining items in the collection have the expected server_profile, given that an empty iterator returns true for `.all` https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.all.
