### ISSUE TITLE
replace WriteConfStep with `lctl replace_nids`

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1376]
Replace the `WriteConfStep` with `lctl replace_nids` in Rust, and then delete the corresponding action plugin writeconf_target.

**Comment by mkpankov** [comment]
So I found [`writeconf_target`](https://github.com/whamcloud/iml-agent/blob/b7f152d7ca7339cc8312888505b7d9eb0058ea01/chroma_agent/action_plugins/manage_targets.py#L35), it definitely looks like a lot more than simply setting up the `nids`.

So, next are several questions.

1. Since we want to replace that, is that correct that we would replicate it's entire API?
```
def writeconf_target(
    device=None,
    target_types=(),
    mgsnode=(),
    fsname=None,
    failnode=(),
    servicenode=(),
    param=None,
    index=None,
    comment=None,
    mountfsoptions=None,
    network=(),
    erase_params=False,
    nomgs=False,
    writeconf=False,
    dryrun=False,
    verbose=False,
    quiet=False,
)
```

2. The old plugin invokes `tunefs.lustre` rather than `lctl` - does it mean in the new one we have to do all the same actions just not with `tunefs` but with `lctl`?

3. The task entails implementing a new action plugin in Rust like those I've developed previously - is that correct?

**Comment by jgrund** [comment]
`writeconf_target` is exposed as an action plugin from that repo.

On the manager side, the one place it's invoked is in the `WriteConfStep` here:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/77426759c79efa59347376e274586daea9e825b0/chroma_core/models/host.py#L1596

`WriteConfStep` is also only used in one place and that's within the `UpdateNidsJob` here:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/77426759c79efa59347376e274586daea9e825b0/chroma_core/models/host.py#L1686-L1698

We can replace that one usage with `lctl replace_nids` using the rust action plugin that already exists here:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/77426759c79efa59347376e274586daea9e825b0/iml-agent/src/action_plugins/action_plugin.rs#L37

Once that's done, all the code referencing `write_conf` can be removed, as it's single usage will also have been removed.

In order to invoke the rust action plugin, you will need to create a step that wraps it, and then use that step where `WriteConfStep` was previously being used.

Here are some very simple Steps that invoke rust plugins as a reference point:

https://github.com/whamcloud/integrated-manager-for-lustre/blob/77426759c79efa59347376e274586daea9e825b0/chroma_core/models/ntp.py#L39-L76

More info on the replace_nids command can be found here: 

http://doc.lustre.org/lustre_manual.xhtml#lustremaint.changingservernid

**Comment by jgrund** [comment]
Needs Python agent code removal.
