### ISSUE TITLE
per MDT operations shows both between short-term and long-term series

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1788]
The per MDT operations chart shows both short-term and long-term series. There is perhaps a extra group by needed.

![Screen Shot 2020-04-15 at 12 13 26 PM](https://user-images.githubusercontent.com/458717/79362622-d05c3a00-7f14-11ea-986b-75c6c35e6b50.png)

**Comment by ip1981** [comment]
Which/what should it show instead?

**Comment by jgrund** [comment]
The series should be merged (as they have non-overlapping timestamps) into a single series. I.E. there should only be one getattr / statfs.

**Comment by ip1981** [comment]
The query provides correct grouping, but it returns two columns: `difference` and `mean_diff_samples`:

```
name: target
tags: name=getattr
time                difference mean_diff_samples
----                ---------- -----------------
1587400765927481980 0          
1587400776928287323 0          
1587400787932360434 0  
...        
```
We see those two columns as duplicates for each `name` ("getattr", "statfs"). This can be fixed by using columns aliases, but I am not sure this is right.

There is another problem with the `mean_diff_samples` subquery: `AND time <= now() - 1d AND  time >= now() - 1d`, so the result is always empty.

**Comment by johnsonw** [comment]
Are you able to use a `group by` to merge them?

**Comment by ip1981** [comment]
> Are you able to use a `group by` to merge them?

No, when I group one more time I get _three_ columns :)

![3](https://user-images.githubusercontent.com/131844/79892136-59d2a700-8402-11ea-9fe5-155cb15ee8f3.png)

I am thinking about `SELECT * (SELECT ... AS "iops" ...), (SELECT ... AS "iops" ...) GROUP BY "name"` with the only difference being `AS "iops"` in the both subqueries.
