### ISSUE TITLE
Intermittent test failure: action_plugins::lpurge::lpurge_conf_tests::works

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#1826]
Rust unit testing has an intermittent failure:

https://github.com/whamcloud/integrated-manager-for-lustre/runs/617943042

<img width="1443" alt="Screen Shot 2020-04-25 at 9 37 46 AM" src="https://user-images.githubusercontent.com/458717/80281359-83c4eb80-86d8-11ea-8925-6aee8ffc7d47.png">

**Comment by ip1981** [comment]
https://github.com/whamcloud/integrated-manager-for-lustre/blob/66f9e321f38814cab5e9795ac22715163cc9dbe6/iml-agent/src/action_plugins/lpurge.rs#L96

**Comment by ip1981** [comment]
This is bad. Environment vars are per process, I bet we have a race.

**Comment by jgrund** [comment]
Yes, I suspect that's the case.

**Comment by jgrund** [comment]
> Solution: do not set SOCK_DIR in tests, use some fallback in postoffice.

Or extract the bit being tested from the bit that reads env vars

**Comment by ip1981** [comment]
I know I wrote it, but what exactly are we testing? :)

**Comment by ip1981** [comment]
I guess we can use [Redactions](https://github.com/mitsuhiko/insta#redactions) to eliminate "socket".

**Comment by ip1981** [comment]
Ok, I see the main issue here:

Since https://github.com/whamcloud/integrated-manager-for-lustre/commit/7caf1c86975b23bd0cb2b790d9a351fef06a06f7 the Display instances depend on the environment, in other words, they are impure. This has to be fixed on its own. I had a vague feeling that I was abusing the Display trait, now I am sure of it.

So I think the socket vars (`listen_socket` and `iml-socket`) have to be fields of the corresponding structures.
