### ISSUE TITLE
docker integration tests fail to download iml-docker

### ISSUE THREAD

**Issue by johnsonw** [whamcloud/integrated-manager-for-lustre#1891]
Occasionally the integration test will fail when trying to download the recently built iml-docker package from jenkins:
```
Error downloading packages:
iml-docker-0.2.0-1.1589224359.el7.x86_64: [Errno 256] No more mirrors to try.
```

After waiting a while you can try downloading from the same url and it will continue to give a 404. This appears to be an issue in jenkins. An example build with this issue can be found at https://build.whamcloud.com/view/IML/job/manager-for-lustre/478/execution/node/38/log/

**Comment by johnsonw** [comment]
This might be due to the build expiring after a certain period of time. I might just close this for now.

**Comment by jgrund** [comment]
The URL that's trying to be fetched is: https://build.whamcloud.com/job/manager-for-lustre/478//artifact/integrated-manager-for-lustre/_topdir/RPMS/x86_64/iml-docker-0.2.0-1.1589224359.el7.x86_64.rpm

If you look at the pipeline steps for 478, you can see the build step only took 12ms. https://build.whamcloud.com/view/IML/job/manager-for-lustre/478/flowGraphTable/

So, the issue to figure out is why the build was that short.

**Comment by jgrund** [comment]
And if you look at the console for 478, you can see it was restarted from #467.

`Restarted from build #467, stage Test`

So, there isn't actually an issue here. What happened is there was a test only rebuild of 467, and then there was another test only rebuild of 478, which will always fail since 478 never ran the build stage.
