### ISSUE TITLE
Refactor SSI testing to use snapshotting

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#327]
Currently, SSI testing does a best-effort approach to clean up between tests. This has proven to be problematic in a few regards:

1. Problems are difficult to diagnose as we not only have to take into account product code, but cleanup code + all runs that came before.
2. We are forcing disk cleanup and teardown without an understanding of the full SUT. For example, we create zpools over existing zpools and running dd on shared storage from multiple hosts in parallel, and trying to move pools at the same time pacemaker / corosync are monitoring targets. 

Instead we can move to a model where we snapshot at the start and restore between tests. This will allow us to avoid cleanup between tests, and ensure we start at the same state each time. This will allow for greater determinism and avoid debugging of failures that are caused by the inter-test cleanup code.

We could use a pipeline of jenkins jobs to first create snapshots of a given build, then reuse those snapshots in child jobs. We could even chunk and parallelize the tests in downstream jobs as well.

**Comment by jgrund** [comment]
> Storage server deployment is very expensive in terms of time and we currently only do it once per (for example) SSI test run.

What do you mean by deployment.

Also, I'm for sure willing to take a hit on time to test in trade for some determinism. We currently spend lot's of engineering time debugging SSI failures related to setup / teardown.

Don't forget I mentioned running tests in parallel as well.

**Comment by brianjmurrell** [comment]
> What do you mean by deployment.

The things that happen when you add a storage server, such as validating the host, choosing a profile,  installing RPMS, DKMS building kernel modules (until #324 can be proven and landed).  Currently this step takes about an hour.

> Also, I'm for sure willing to take a hit on time to test in trade for some determinism.

Willing to add an hour per SSI sub-test?

> We currently spend lot's of engineering time debugging SSI failures related to setup / teardown.

I agree.  I think some time needs to be spent there fixing the known issues and just generally looking over the process and deciding if what we are doing is really how a teardown should be done.  This is ultimately something that needs to be done in any case so that these tests can be run on real hardware where VM-style snapshots don't exist.

> Don't forget I mentioned running tests in parallel as well.

Parallel or not, I'm not sure we have the capacity to add an hour per SSI/EFS subtest.

**Comment by brianjmurrell** [comment]
I'm not against snapshotting.  We just need to be careful where we do it and post-deployment is the most efficient.  That makes adding it more difficult though since it needs to become part of the test framework and happen after the first host deployment in a series of tests, and be restored at host deployment in any post-first-test tests.

**Comment by jgrund** [comment]
> The things that happen when you add a storage server, such as validating the host, choosing a profile, installing RPMS, DKMS building kernel modules (until #324 can be proven and landed). Currently this step takes about an hour.

Right, was thinking this part would be part of the snapshot.

**Comment by brianjmurrell** [comment]
> Right, was thinking this part would be part of the snapshot.

Indeed, which means the snapshotting has to be baked into the test framework to happen after the first test's deployment (whatever that test is) but a restore happens in the same place on subsequent tests.  It's that part that complicates it a little.  Not horribly, but just moves it a bit outside the realm of "really easy".

But since tests don't always use all nodes, it would be more likely to be some kind of pre-test-run to do a deployment to all nodes and then snapshot those before starting the test run.

**Comment by jgrund** [comment]
As an addendum to this, @brianjmurrell brought up the idea of a stack of setup / teardown operations, where the teardown op is pushed on the stack once the setup op executes. In this way, you get setup / teardown for different types of operations in a reusable / composable way.

I think this can be modeled as a type of delayed computation. The idea would be to build a pipeline of operations, and run your test at the center of the pipeline. If anything in the pipeline fails, the teardown for (completed?) steps will execute.

``` 
    let monitoredZfs =  mdadm >> vg >> zfs >> lustre
    monitoredZfs(testCase).run()
```

**Comment by brianjmurrell** [comment]
Indeed.  This should go even deeper than just block device configuration though.  Every action should have an unwind action automatically pushed on to the stack.  So if the test creates a lustre filesystem, the removal of that filesystem is automatically pushed onto the _unwind stack_ so that if the test does not remove it before it is done, it is removed automatically by the test framework `tearDown()`.

An important aspect is though, if the test does remove the filesystem before it's done, that item needs to be removed from the _unwind stack_.  This of course could be done automatically by the filesystem removal function with a reference to the item on the stack that is attached to the filesystem object given to the removal function.

**Comment by jgrund** [comment]
I'm not sure that spreading the state to the test layer is the best approach, when you could encapsulate the entire operation and not leak the abstraction. 

> An important aspect is though, if the test does remove the filesystem before it's done, that item needs to be removed from the unwind stack. This of course could be done automatically by the filesystem removal function with a reference to the item on the stack that is attached to the filesystem object given to the removal function.

Or, all teardown could check for expected state before performing the teardown, instead of us having to mutate the cleanup stack.

**Comment by jgrund** [comment]
I don't think this will ever happen in current SSI, but https://github.com/whamcloud/integrated-manager-for-lustre/pull/1495 has snapshotting built-in to each of the setup steps.
