### ISSUE TITLE
ZFS Snapshots

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#540]
It would be useful for IML to have the ability
to manage snapshots. This includes:

- Ability to schedule snapshots for filesystems at some regular interval (possibly with some retention rules).
- Ability to take adhoc snapshot on filesystem(s).
- Ability to view / delete previous snapshots.
- Ability to rollback to a given snapshot.
- Ability to rename a snapshot.
- Take snapshot at key points (I.E. lustre upgrade).

Given all of these features, we will also want to tie the functionality into a given zpool.
This means being able to click on a zpool / dataset in the GUI and see info about that pool, along with any
snapshots on it's datasets.

Overall we will want an aggregate view of snapshots and an individual view over pools / datasets.

**Comment by adilger** [comment]
It would be useful to also create `automount` maps so that on login or other interactive user nodes could automatically mount names snapshots (e.g. "`yesterday`") when they change into the appropriate subdirectory (e.g. `/mnt/testfs/.lustre/snapshots/yesterday/` or `/mnt/testfs-yesterday/` or similar).   The "nice name" to "snapshot name" mapping would be updated daily when new snapshots are created.
