### ISSUE TITLE
bundled Robinhood not working with Lustre 2.10.5

### ISSUE THREAD

**Issue by jgrund** [whamcloud/integrated-manager-for-lustre#731]
When Attempting to install a Robinhood server I am seeing:

```
Error: nothing provides liblustreapi.so.1()(64bit) needed by robinhood-lhsm-2.5.5-2.lustre.el7.centos.x86_64
```

We should upgrade to a newer robinhood that supports Lustre 2.10.x

**Comment by utopiabound** [comment]
This should be fixed with upgrade to Lustre 2.12.1 (#902)

**Comment by utopiabound** [comment]
We no longer get an error about `liblustreapi.so.1` not being provided, but we do get the following error:
```
--> Processing Dependency: httpd for package: php-5.4.16-46.el7.x86_64
Package httpd is obsoleted by python2-iml-manager, but obsoleting package does not provide for requirements
```
Because `python2-iml-manager` is in the same repository as iml-agent, it's obsoletes are used in package resolution and because it obsoletes httpd, it's placed as a replacement in the dependency solving tree.

*WORKAROUND*
Add `--exclude python2-iml-manager` to yum installation for robinhood rpms.

**Comment by jgrund** [comment]
We should just remove the obsoletes for `httpd`.
